version: '3.9'
services:
  mysql:
    extends:
      file: docker-compose.yml
      service: mysql
    volumes:
      - ./config/database/sample_data.sql:/docker-entrypoint-initdb.d/2.sql
      - /var/lib/mysql  # This will override the db-data volume from the base file
