{
 "title": "LifeSync Monitoring",
 "description": "Monitoring Key LifeSync Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "JDBC Active Connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hikaricp_connections_active ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Page Visits",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(http_server_requests_seconds_count{uri=\"/**\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_committed_bytes) / 1024^2",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(process_cpu_usage[$__rate_interval]) * 100",
     "legendFormat": "Process CPU Usage"
    },
    {
     "expr": "avg_over_time(system_cpu_usage[$__rate_interval]) * 100",
     "legendFormat": "System CPU Usage"
    }
   ]
  },
  {
   "title": "Page Visit Breakdown",
   "type": "stat",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "round(increase(http_server_requests_seconds_count{uri!=\"/**\", uri!=\"/actuator/prometheus\", status=\"200\"}[$__rate_interval]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "round(increase(http_server_requests_seconds_count{uri=\"/**\",}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}